### Variables globales
@baseUrl = http://localhost:3000/api/books

###############################################################################
# REQ-02
###############################################################################

### 2.1 GET /api/books 
GET {{baseUrl}}
Content-Type: application/json


###############################################################################
# REQ-03 
###############################################################################

### 3.1 GET /api/books/1 
GET {{baseUrl}}/1
Content-Type: application/json

### 3.2 GET /api/books/999 
GET {{baseUrl}}/999
Content-Type: application/json


###############################################################################
# REQ-04 · Crear libros 
###############################################################################

### 4.1 POST /api/books 
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "The way of kings",
  "author": "Brandon Sanderson",
  "year": 2010
}

### 4.2 POST /api/books 
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
}


###############################################################################
# REQ-05 
###############################################################################

### 5.1 POST /api/books 
POST {{baseUrl}}
Content-Type: application/json

{
  "author": "Robert C. Martin",
  "year": 2008
}

### 5.2 POST /api/books 
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "   ",
  "author": "Robert C. Martin",
  "year": 2008
}

### 5.3 POST /api/books 
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "year": 1999
}

### 5.4 POST /api/books 
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "author": "Andrew Hunt",
  "year": "mil novecentos noventa y nueve"
}


###############################################################################
# REQ-06
###############################################################################

### 6.1 DELETE /api/books/2 
DELETE {{baseUrl}}/2
Content-Type: application/json

### 6.2 DELETE /api/books/2 
DELETE {{baseUrl}}/2
Content-Type: application/json


###############################################################################
# REQ-07 
###############################################################################

### 7.1 PATCH /api/books/1
PATCH {{baseUrl}}/1
Content-Type: application/json

{
  "year": 2018
}

### 7.2 PATCH /api/books/999
PATCH {{baseUrl}}/999
Content-Type: application/json

{
  "title": "Libro Inexistente"
}

###############################################################################
# REQ-08 
###############################################################################

### 8.1 GET /api/books?author=Robert
GET {{baseUrl}}?author=Brandon
Content-Type: application/json

### 8.2 GET /api/books?year=2018
GET {{baseUrl}}?year=2018
Content-Type: application/json

### 8.3 GET /api/books?author=Robert&year=2008
GET {{baseUrl}}?author=Robert&year=2018 
Content-Type: application/json

### 8.4 GET /api/books?author=Dostoievski
GET {{baseUrl}}?author=Dostoievski
Content-Type: application/json